name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Replace with the version your app uses

      - name: Install dependencies
        run: npm install # Install backend dependencies

      - name: Run tests
        run: npm test # Run the tests defined in your backend project

      - name: Lint the code (Optional)
        run: npm run lint # Lint the code if you are using eslint
